<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/george_half_ass_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework

Do some exercises use the functions in pandas against your own data

do count by year

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("anandshaw2001/netflix-movies-and-tv-shows")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/anandshaw2001/netflix-movies-and-tv-shows?dataset_version_number=1...

100%|██████████| 1.34M/1.34M [00:00<00:00, 64.9MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/anandshaw2001/netflix-movies-and-tv-shows/versions/1

In [4]:
import pandas as pd
import os

file_path = path + '/netflix_titles.csv'

if os.path.exists(file_path):
    df_netflix = pd.read_csv(file_path)
    print("Netflix data loaded successfully. First 5 rows:")
    display(df_netflix.head())

    print("\nDataFrame Info:")
    df_netflix.info()
else:
  print("not found")

Netflix data loaded successfully. First 5 rows:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [16]:

#df = df_netflix
df.loc[df['country'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8718,s8719,Movie,Westside vs. the World,Michael Fahey,"Ron Perlman, Louie Simmons",NaN,"August 9, 2019",2019,TV-MA,96 min,"Documentaries, Sports Movies",A look into the journey of influential strengt...
8759,s8760,Movie,World's Weirdest Homes,Storm Theunissen,Charlie Luxton,NaN,"February 1, 2019",2015,TV-PG,49 min,Movies,From a bubble-shaped palace to an island built...
8783,s8784,TV Show,Yoko,NaN,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...",NaN,"June 23, 2018",2016,TV-Y,1 Season,Kids' TV,"Friends Mai, Oto and Vik's games at the park b..."
8785,s8786,TV Show,YOM,NaN,"Sairaj, Devyani Dagaonkar, Ketan Singh, Mayur ...",NaN,"June 7, 2018",2016,TV-Y7,1 Season,Kids' TV,"With the mind of a human being, and the body o..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

#Homework


##1

def myFunc(row):
    # look at all columns
    # if one is Nan
    # return true


df.map(myFunc)


##2

Use a dictionary to make example of download some other data.



Homework:  give an example of when you would sum across rows and give an example when you would sort across columns

The "axis" parameter in Pandas refers to the direction along which an operation is performed on data structures like Series and DataFrames. In a Series, which is a one-dimensional array of values, there is only "axis 0" representing the single dimension. On the other hand, a DataFrame, a two-dimensional data structure similar to a table, has both "axis 0" for rows and "axis 1" for columns.

# sum across row or column

Give an example using axis
axis = 0 rows

df = pd.DataFrame({

      "a" : [1,2,3,4],
      "b" : [5,6,7,8]
})


# add across rows

df.sum(axis=0)

In [17]:

df = pd.DataFrame({

      "a" : [1,2,3,4],
      "b" : [5,6,7,8]
})


# add across rows
df

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [20]:
df.sum(axis=0)

a    10
b    26
dtype: int64

In [25]:
df.sum(axis=1)

0     6
1     8
2    10
3    12
dtype: int64

In [22]:
football=pd.DataFrame({
    "game1" : [1,2,3,4],
      "game2" : [5,6,7,8]

})

football

   game1  game2
0      1      5
1      2      6
2      3      7
3      4      8

In [23]:
football.sum(axis=0)

game1    10
game2    26
dtype: int64

In [24]:
# sum across columns
football.sum(axis=1)

0     6
1     8
2    10
3    12
dtype: int64

In [10]:
df.iloc[8803]

show_id                                                     s8804
type                                                      TV Show
title                                                 Zombie Dumb
director                                                      NaN
cast                                                          NaN
country                                                       NaN
date_added                                           July 1, 2019
release_year                                                 2018
rating                                                      TV-Y7
duration                                                2 Seasons
listed_in                  Kids' TV, Korean TV Shows, TV Comedies
description     While living alone in a spooky town, a young g...
Name: 8803, dtype: object

In [ ]:
print("Values in 'release_year' column:")
display(df_netflix['release_year'].value_counts().sort_index())

Values in 'release_year' column:

release_year
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     418
2017.0    1164
2018.0    1625
2019.0    1999
2020.0    1878
2021.0    1498
Name: count, dtype: int64